
export enum Input {
    GROUP = "GROUP",
    TEXT= "TEXT",
    PASSWORD = "PASSWORD",
    PHONE = "PHONE",
    SELECT = "SELECT",
    RADIO_GROUP = "RADIO_GROUP",
    CHECK_BOX_GROUP = "CHECK_BOX_GROUP",
    TOGGLE_SWITCH = "TOGGLE_SWITCH",
    DATE_PICKER = "DATE_PICKER",
    FILE_INPUT = "FILE_INPUT",
    TEXT_ADDER = "TEXT_ADDER",
}